### ISSUE TITLE
Syntax Error in ruby3

### ISSUE THREAD

**Issue by zephyrpathsofglory** [moku-io/protobuf_transpiler#1]
```
vendor/bundle/ruby/3.0.0/gems/protobuf_transpiler-1.1.1/lib/protobuf_transpiler.rb:160: syntax error, unexpected ')', expecting local variable or method
  def each_oneof(&)
```

just launch irb in ruby3, and define any method:
```
def a(&)
   p 'test'
end
```
will report SyntaxError

**Comment by nicologreggio-Moku** [comment]
Hi.

Thank you for your feedback. You're right: anonymous block argument was introduced in Ruby 3.1.

We just released version [1.1.2](https://github.com/moku-io/protobuf_transpiler/releases/tag/1.1.2) with the fix to the issue.

Have a nice day.
